### ISSUE TITLE
Korkmaz

### ISSUE THREAD

**Issue by AdamMorrisonsStache** [sumeshsharma1/fantasybball#4]
I was using the Sumesh's Fantasy Basketball Dashboard and I entered in a lot of the values that I was supposed to do and I chose my team and I said how many players and I said I wanted it to keep a player I like and then I selected last 7 days which I think means the last seven days of the week but doesn't actually mean the last seven games played which it really should because some players play more games in a week than others due and then I said for it to run and it kinda took a while but then it gave me a list of players and one of the players was name Furkan Korkmaz and I don't know who that is but it doesn't sound like a real person but then I looked him up on basketball reference and it seems like he is actually a basketball player for the Philadelphia Seventy Sixers but I'm like hmm maybe he is really good and I looked at his statistical play and no he isn't very good so I'm pretty sure this is a bug.

**Comment by sumeshsharma1** [comment]
Hello,

The fantasy basketball dashboard exists only as a supplement to help the user make wise decisions relating to their basketball strategy. It does not serve as a replacement for good decision making, well done research, and generally good basketball knowledge.
